### ISSUE TITLE
Description of the data

### ISSUE THREAD

**Issue by yaz-saleh** [UBC-MDS/532-group11#3]
In your proposal, briefly describe the dataset and the variables that you will visualize. If your are planning to visualize a lot of columns, provide a high level descriptor of the variable types rather than listing every single column. For example, indicate that the dataset contains a variety of categorical variables for demographics and provide a brief list rather than describing every single variable. You may also want to consider visualizing a smaller set of variables given the short duration of this project. This might include brief exploratory data analysis for you to grasp what could be interesting aspects to look at in your data. We will not be grading the EDA aspect, but feel free to include your EDA notebooks in the public GitHub repo, so that you have everything in one place.

**Comment by yhchen20** [comment]
We will be visualizing a dataset of approximately 10,000 movies. Each movie has 21 associated variables that describe the basic information of movie (genres, runtime, release date), the financial status (budget, revenue) of the movie, the staff (casts, directors, production company) of the movie, and the performance (popularity) of the movie. Using this data we will also derive a new variable, which is the gross profit that is calculated by revenue minus budget.

**Comment by yaz-saleh** [comment]
## Description of the data

The dataset contains information about 10,000+ Hollywood movies. A mix of categorical, text, and numeric attributes provide specific information about each movie. This includes attributes describing the nature and timing of the movie itself (`genres`, `runtime`, `release date`), how well it was received (`vote count`, `vote average`), as well as its financial matters (`budget`, `revenue`).
