### ISSUE TITLE
Research questions and usage scenarios

### ISSUE THREAD

**Issue by yaz-saleh** [UBC-MDS/532-group11#4]
For this it can be helpful to create a brief persona description of a member in your intended target audience and write small user story for what they might do with your app. User stories are typically written in a narrative style and include the specific context of usage, tasks associated with that use context, and a hypothetical walkthrough of how the user would accomplish those tasks with your app. If you are using a Kaggle dataset, you may use their "Overview (inspiration)" to create your usage scenario.

**Comment by yhchen20** [comment]
Alexi is a investment manager in Alpha Investment Corporation and he wants to understand what factors lead to high return of investment in movies. Now he has three different scenarios but limited fund, so he needs to make the investment decision. He wants to be able to explore a dataset in Ofer to compare the effect of different variables on  return of investment in movies. When Mary logs on to the “Movie App”, she will see an overview of all the available variables about the movies. He can filter out variables for different genres, casts, directors, production companies to see the performance of a specific group of movies. He hypothesizes that genres is the most important features that will influence the return of investment, and he decides to pick a scenario of action movie to invest.

**Comment by yaz-saleh** [comment]
J. Doe runs a start-up movie production company in North America. Due to limited venture capital in the entertainment industry in 2020-2021, J. Doe wants to ensure that he only selects profitable movies for production in his company. In order to [identify] the type of profitable movies, J. Doe wants to [explore] a dataset that compares how different movie attributes are related to revenue...
