### ISSUE TITLE
Description of the app

### ISSUE THREAD

**Issue by yaz-saleh** [UBC-MDS/532-group11#5]
In this description you are not required to use terminology specific to Dash apps (i.e. widgets, components, etc...) or make reference to specific Python or R libraries. Your sketch can be hand-drawn or mocked up using a graphics editor. If you can show the app visual design & interaction design in a single image that is ideal, but if you need more space to show some other planned features of your app you can include max three images for this proposal.

The description should be about 200-300 words and live in the README.md file of your GitHub.com repository. The sketch should be linked in the README.md file of your GitHub.com repository underneath the high level description so that the image shows up on GitHub.

**Comment by rahulkuriyedath** [comment]
Top left: Genre vs rating (heatmap)
Top Right: Genre vs budget
Bottom Left: Find an actor (based on genre, budget and possibly year)
Bottom right: Best release month (month vs profit for selected genre)

**Comment by rahulkuriyedath** [comment]
Closing since this has been completed and pull request created.
